name: Deploy ThumbStack Restaurants

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packeages
        id: install
        run: npm i && cd client && npm i

      - name: testing 
        id: test
        run: cd client && npm test
      
      - name: deploy
        id: deploy
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action

        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "thumbstackrestaurant" #Must be unique in Heroku
          heroku_email: "mayurbhowad1995@gmail.com"